# Generated by Django 3.0.8 on 2020-08-03 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('action', models.IntegerField(choices=[(1, 'currency inserted'), (2, 'cancelled by user'), (3, 'item selected by user'), (4, 'refund amount'), (10, 'called by machine'), (11, 'Admin add product'), (12, 'Admin currency withdraw')])),
                ('activity_log', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('denomination', models.IntegerField(blank=True, choices=[(10, '10'), (20, '20'), (50, '50'), (100, '100')], null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='machine.Products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[(1, 'Ready'), (2, 'Currency Inserted'), (3, 'Dispensing Item'), (4, 'Out of Stock'), (10, 'Under Maintenance')], default=1)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.MachineTransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
